// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2R426TNxDiKe9yABVDpn-0ZRW6wPMBTw',
    appId: '1:576434898701:web:0e2756ea584c01ccbd1244',
    messagingSenderId: '576434898701',
    projectId: 'task-management-4fa93',
    authDomain: 'task-management-4fa93.firebaseapp.com',
    storageBucket: 'task-management-4fa93.appspot.com',
    measurementId: 'G-4LK30HNFFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpIsp2RVSvL-q1MXfGbsEyFg9jlji8PM',
    appId: '1:576434898701:android:253bd0e97403e803bd1244',
    messagingSenderId: '576434898701',
    projectId: 'task-management-4fa93',
    storageBucket: 'task-management-4fa93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfjSf8A18ClErsdYQ3pW09Dat19zwDng',
    appId: '1:576434898701:ios:e273af84ea0050ffbd1244',
    messagingSenderId: '576434898701',
    projectId: 'task-management-4fa93',
    storageBucket: 'task-management-4fa93.appspot.com',
    androidClientId: '576434898701-0ph5ch5k3nmj5j946cd2ed5lehrk83mp.apps.googleusercontent.com',
    iosClientId: '576434898701-n2ekver81jpe05q5sk0d15hrpuc780ul.apps.googleusercontent.com',
    iosBundleId: 'com.samuel.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfjSf8A18ClErsdYQ3pW09Dat19zwDng',
    appId: '1:576434898701:ios:e273af84ea0050ffbd1244',
    messagingSenderId: '576434898701',
    projectId: 'task-management-4fa93',
    storageBucket: 'task-management-4fa93.appspot.com',
    androidClientId: '576434898701-0ph5ch5k3nmj5j946cd2ed5lehrk83mp.apps.googleusercontent.com',
    iosClientId: '576434898701-n2ekver81jpe05q5sk0d15hrpuc780ul.apps.googleusercontent.com',
    iosBundleId: 'com.samuel.taskManagement',
  );
}
